### ISSUE TITLE
Add to public Julia Registry?

### ISSUE THREAD

**Issue by magerton** [npfrazier/HaltonSequence.jl#9]
Hi @npfrazier, thank you for merging the PR so quickly. Can we register this package publicly? It'll simplify using it as a dependency. 

I'm happy to help maintain the pkg, tag the releases, register it if that would be helpful -- I think I'd probably just need maintain privileges. 

-M

**Comment by magerton** [comment]
Thank you, @npfrazier! I'll tag the release, update the various coverage thingys, and add it to JuliaHub's Package Registrator

**Comment by magerton** [comment]
@npfrazier, afraid I don't have permissions to add this to Julia's Registrator, which is at <https://juliahub.com/ui/Packages/Registrator/Obz5J/1.5.0>. At this point, it's you as the repo owner who can do that. Sorry to be filling your inbox this morning!

**Comment by npfrazier** [comment]
It turns out there already is a registered package out with similar (if not equivalent) functionality. https://github.com/tobydriscoll/HaltonSequences.jl

**Comment by magerton** [comment]
The other package is slower compared to Halton.jl

**Comment by npfrazier** [comment]
Going to attempt registry under the name FastHalton.jl. This name reflects the added virtue relative to the existing package options. Specifically, an algorithm someone else made that reduces computational time.

**Comment by magerton** [comment]
> Going to attempt registry under the name FastHalton.jl. This name reflects the added virtue relative to the existing package options. Specifically, an algorithm someone else made that reduces computational time.

And the title of the paper: ["Fast, portable, and reliable algorithm for the calculation of Halton numbers"](https://www.sciencedirect.com/science/article/pii/089812219390307H)

**Comment by npfrazier** [comment]
For Julia 1.6 or greater you can now get FastHalton from the public repository. Enjoy.

**Comment by magerton** [comment]
> For Julia 1.6 or greater you can now get FastHalton from the public repository. Enjoy.

Sweet! Thanks, Nick! 👍
